# Hugs å legge til dei nye klassene under ScreenManagement!

#: import ScreenManager kivy.uix.screenmanager.ScreenManager
#: import Screen kivy.uix.screenmanager.ScreenManager


ScreenManagement:

	FrontScreen:
	MainWidget:
	KlimaScreen:
	HistorieScreen:
	Veibeskrivelser:
	KulturScreen:
	SelectionScreen:
        id: selection_screen
        name: 'SelectionScreen'
	CustomParkControl:


	Museum:
	Rockheim:
	RockheimInfo:
	TrondelagFolkemuseum:
	TrondelagFolkemuseumInfo:
	RingveMuseum:
	RingveMuseumInfo:
	Vitenskapsmuseet:
	VitenskapsmuseetInfo:
	Rustkammeret:
	RustkammeretInfo:
	NordenfjeldskeKunst:
	NordenfjeldskeKunstInfo:
	TrondheimKunstmuseum:
	TrondheimKunstmuseumInfo:
	NorskeDovemuseum:
	NorskDovemuseumInfo:
	JodiskeMuseum:
	JodiskMuseumInfo:
	TrondheimSjofartsmuseum:
	TrondheimSjofartsmuseumInfo:

	HistoriskeSteder:
	Nidarosdomen:
	NidarosdomenInfo:
	Stiftsgarden:
	StiftsgardenInfo:
	GamleBybro:
	GamleBybroInfo:
	KristianstenFestning:
	KristianstenFestningInfo:
	Erkebispegarden:
	ErkebispegardenInfo:
	Munkholmen:
	MunkholmenInfo:
	Bakklandet:
	BakklandetInfo:
	VarFrueKirke:
	VarFrueKirkeInfo:

	Kultur:
	Vitensenteret:
	VitensenteretInfo:
	KunsthallTrondheim:
	KunsthallTrondheimInfo:
	LitteraturhusetTrondheim:
	LitteraturhusetTrondheimInfo:
	KultursenteretISAK:
	KultursenteretISAKInfo:

	Natur:
	Burmaklippen:
	BurmaklippenInfo:
	Geitfjellet:
	GeitfjelletInfo:
	Vattakammen:
	VattakammenInfo:
	Ladestien:
	LadestienInfo:

	MatDrikke:
	Tyholttarnet:
	TyholttarnetInfo:
	IlaBrannstasjon:
	IlaBrannstasjonInfo:
	Antikvariatet:
	AntikvariatetInfo:
	ArvesolvetFolkekafe:
	ArvesolvetFolkekafeInfo:
	CafeNim:
	CafeNimInfo:
	CafeNiMuser:
	CafeNiMuserInfo:
	RosenborgDampbakeri:
	RosenborgDampbakeriInfo:
	SellenraaBokBar:
	SellenraaBokBarInfo:
	TrondheimMikrobryggeri:
	TrondheimMikrobryggeriInfo:
	CafeLokka:
	CafeLokkaInfo:
	BakklandetSkydsstasjon:
	BakklandetSkydsstasjonInfo:

	Aktiviteter:
	Klatresenter:
	KlatresenterInfo:
	Turnhall:
	TurnhallInfo:
	Bowling:
	BowlingInfo:
	Trampolinepark:
	TrampolineparkInfo:
	GokartOgLazerx:
	GokartOgLazerxInfo:
	EscapeReality:
	EscapeRealityInfo:


#Framskjermen
<FrontScreen>:
	#namnet som vert brukt seinare til referering
	name: "front"

	#definerar bakgrunnsbiletet
	canvas.before:
		#sjølve biletet
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'framside/adressabygget.jpg'
        #diffust overlegg over biletet
		Color:
			rgba: 0.976470588,0.976470588,0.976470588,0.7
		Rectangle:
			pos: self.pos
			size: self.size

	#definerer at sida skal vere eit boxlayout med eit bilete fyrst, så ein knapp	
    BoxLayout:
    	orientation: 'vertical'
		Image:
			source: 'framside/adr_logo.png'
			allow_stretch: False
			keep_ratio: False
		Image:
			source: 'framside/elsys_lite_trans.png'
			allow_stretch: False
			keep_ratio: False
        Button:
            text: 'Til menyen'
            font_size: 70
            color: 0.0705882, 0.4784313725, 0.75294117647, 1
            background_color: [1, 1, 1, 0]
            on_release: root.manager.current = 'main'



#Meny-sida
<MainWidget>:
	name: "main"

    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size: root.size
			rows: 1

			#overskrifta til sida
			Label:
				text: "MENY"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			size: root.size
			cols: 3

			Button:
				text: 'Klimavalg'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				font_size: 80
				on_press: root.manager.current = 'klima'
			Button:
				text: "Historisk"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				font_size: 80
				on_press: root.manager.current = 'historisk'
			Button:
				text: "Severdigheter"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				font_size: 80
				on_press: root.manager.current = 'SelectionScreen'
			Button:
				text: "Styr parken"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				font_size: 80
				on_press: root.manager.current = 'parkkontroll'
            Button:
				text: "Veibeskrivelser"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				font_size: 80
				on_press: root.manager.current = 'veibeskrivelser'
			Button:
				text: "Arrangement"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				font_size: 80
				on_press: root.manager.current = 'arrangement'




		GridLayout:
			size: root.size
			rows: 2

			Label:

			Button:
				text: "Framskjerm"
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				font_size: 70
				on_press: root.manager.current = 'front'



#Klimaval-modulen
<KlimaScreen>:
	name: "klima"

    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size: root.size
			rows: 1

			Label:
				text: "Klimavelgeren"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			cols: 4
			rows: 2

			Image:
				source: 'klimabilde/syden.jpeg'
				allow_stretch: True
				keep_ratio: False
			Image:
				source: 'klimabilde/antarktis.jpeg'
				allow_stretch: True
				keep_ratio: False
			Image:
				source: 'klimabilde/jungel.jpeg'
				allow_stretch: True
				keep_ratio: False
			Image:
				source: 'klimabilde/hav.jpeg'
				allow_stretch: True
				keep_ratio: False
			Button:
				text: 'Syden'
				font_size: 50
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.syden(self)
			Button:
				text: "Antarktis"
				font_size: 50
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.antartktis(self)
			Button:
				text: "Jungel"
				font_size: 50
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.jungel(self)
			Button:
				text: "Hav"
				font_size: 50
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.hav(self)
				



		GridLayout:
			size: root.size
			rows: 2

			Label:

			Button:
				text: "Tilbake til menyen"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				font_size: 70
				on_release: root.manager.current = 'main'

<KulturScreen>:
	name: 'arrangement'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
    	orientation: 'vertical'
    	
        Label:
        	text: 'Arrangement'
        	color: 0.0705882, 0.4784313725, 0.75294117647, 1
        	font_size: 100
        	size_hint: (1, 0.2)
        

        #Ein rullbar modul der dei ulike historiske plassane er lista
        ScrollView:

			GridLayout:
				rows: 1
				size_hint_y: None
				height: 3000

				Image:
					source: 'kulturoversikt.jpg'
					allow_stretch: False
					keep_ratio: False

        Button:
            text: 'Til menyen'
            color: 0.0705882, 0.4784313725, 0.75294117647, 1
			background_color: [1, 1, 1, 0.1]
			font_size: 70
            on_press: root.manager.current = 'main'
            size_hint: (1, 0.2)
				
<SelectionScreen>:
    padding: [10, 20]
    spacing: 2

    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: 'vertical'

        GridLayout:
            size_hint: (1, 0.5)
            rows: 2
			
            Label:
                text: "Severdigheitsrulett"
                font_size: 100
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]

            Label:
                text: "Kryss av for aktuelle alternativer"
                font_size: 30
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]

        GridLayout:
            orientation: 'vertical'
            size_hint: (1, 0.7)

            padding: [10, 40]
            cols: 2
            rows: 6
            Label:
                text: "Museum"
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            CheckBox:
                on_active: root.checkbox_museum_cliked(self, self.active)
                size_hint_x: .55
            Label:
                text: "Historiske steder"
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            CheckBox:
                on_active: root.checkbox_historisk_cliked(self, self.active)
                size_hint_x: .55
            Label:
                text: "Kultur"
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            CheckBox:
                on_active: root.checkbox_kultur_cliked(self, self.active)
                size_hint_x: .55
            Label:
                text: "Natur"
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            CheckBox:
                on_active: root.checkbox_natur_cliked(self, self.active)
                size_hint_x: .55
            Label:
                text: "Mat og drikke"
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            CheckBox:
                on_active: root.checkbox_mat_cliked(self, self.active)
                size_hint_x: .55
            Label:
                text: "Aktiviteter"
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            CheckBox:
                on_active: root.checkbox_aktiviteter_cliked(self, self.active)
                size_hint_x: .55

        GridLayout:
            orientation: 'vertical'
            size_hint: (1, 0.11)
            rows: 1
            cols: 2

            Button:
                text: 'Til menyen'
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
			Button:
                text: "Klikk når du er klar"
                on_press: root.screenSelector()
                on_release:
                    root.manager.current = str(root.manager.ids.selection_screen.testScreen)
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]

#Historie-modul
<HistorieScreen>:
	name: 'historisk'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
    	orientation: 'vertical'
    	
        Label:
        	text: 'Historisk'
        	color: 0.0705882, 0.4784313725, 0.75294117647, 1
        	font_size: 100
        	size_hint: (1, 0.2)
        

        #Ein rullbar modul der dei ulike historiske plassane er lista
        ScrollView:

			GridLayout:
				cols: 2
				size_hint_y: None
				height: 1000
        	
				# -----------------------------------------------------
				GridLayout:
					rows: 2
					cols: 1

					Label:
						text: 'Nidarosdomen'
						font_size: 50
						size_hint: (1, 1)
						color: 0.0705882, 0.4784313725, 0.75294117647, 1
						background_color: [1, 1, 1, 0]
					Label: 
						text: 'Den praktfulle Nidarosdomen er Norges opprinnelige erkebiskopkirke, og en av nordens største middelalderkirker. Byggingen ble påbegynt i 1070, og domen har siden stått oppreist over Olav den Helliges grav. Flere av Norges konger er både kronet, viet og gravlagt her. Her kan du delta på både gudstjenester, omvisninger og konserter.'
						text_size: self.width, None
						size_hint_y: None
						height: self.texture_size[1]
						color: 0.0705882, 0.4784313725, 0.75294117647, 1
						background_color: [1, 1, 1, 0]
				GridLayout:
					cols: 1
					rows: 1
					size_hint: (0.2, 0.5)

					Image:
						source: 'severdighetsbilder/Nidarosdomen.jpg'
						allow_stretch: True
						keep_ratio: False
				# -----------------------------------------------------
				GridLayout:
					rows: 2
					cols: 1

					Label:
						text: 'Stiftsgården'
						font_size: 50
						size_hint: (1, 1)
						color: 0.0705882, 0.4784313725, 0.75294117647, 1
						background_color: [1, 1, 1, 0]
					Label: 
						text: 'Stiftsgården er Trondheims kongelige residens, og nordens største trepalé. Gården ble bygget for Cecilie Christine Schøller i 1774-1778. Du kan oppleve den barokk-klassisistiske stilen på Stiftsgården ved å delta på omvisning.'
						text_size: self.width, None
						size_hint_y: None
						height: self.texture_size[1]
						color: 0.0705882, 0.4784313725, 0.75294117647, 1
						background_color: [1, 1, 1, 0]
				GridLayout:
					cols: 1
					rows: 1
					size_hint: (0.2, 0.5)

					Image:
						source: 'severdighetsbilder/stiftsgarden.jpg'
						allow_stretch: True
						keep_ratio: False
				# -----------------------------------------------------
				GridLayout:
					rows: 2
					cols: 1

					Label:
						text: 'Gamle Bybro'
						font_size: 50
						size_hint: (1, 1)
						color: 0.0705882, 0.4784313725, 0.75294117647, 1
						background_color: [1, 1, 1, 0]
					Label: 
						text: 'Gamle Bybro, også kalt “Lykkens Portal”, strekker seg over nidelven ved Bakklandet. Den ble første gang bygget i forbindelse med Kristiansten festning i 1681, og skulle erstatte den tidligere bybroen. Dagens versjon av broen er fra 1861, og hadde opprinnelig broklapper som kunne heises opp og holdes oppe av to utskårne portalene, hvor én av dem fortsatt står igjen.'
						text_size: self.width, None
						size_hint_y: None
						height: self.texture_size[1]
						color: 0.0705882, 0.4784313725, 0.75294117647, 1
						background_color: [1, 1, 1, 0]
				GridLayout:
					cols: 1
					rows: 1
					size_hint: (0.2, 0.5)

					Image:
						source: 'severdighetsbilder/GamleBybro.jpg'
						allow_stretch: True
						keep_ratio: False

				# -----------------------------------------------------
				GridLayout:
					rows: 2
					cols: 1

					Label:
						text: 'Kristiansten festning'
						font_size: 50
						size_hint: (1, 1)
						color: 0.0705882, 0.4784313725, 0.75294117647, 1
						background_color: [1, 1, 1, 0]
					Label: 
						text: 'Kristiansten festning har siden slutten av 1600-tallet stått over Bakklandet i Trondheim, og voktet over Gamle Bybro. Frem til 2001 har Kristiansten blant annet vært benyttet til militært bruk, treningsanlegg, brannvakt og rettersted. I dag er Kristiansten festning administrativt fredet og et av Norges 14 nasjonale festningsverk.'
						text_size: self.width, None
						size_hint_y: None
						height: self.texture_size[1]
						color: 0.0705882, 0.4784313725, 0.75294117647, 1
						background_color: [1, 1, 1, 0]
				GridLayout:
					cols: 1
					rows: 1
					size_hint: (0.2, 0.5)

					Image:
						source: 'severdighetsbilder/KristianstenFestning.jpg'
						allow_stretch: True
						keep_ratio: False

				# -----------------------------------------------------
				GridLayout:
					rows: 2
					cols: 1

					Label:
						text: 'Erkebispegården'
						font_size: 50
						size_hint: (1, 1)
						color: 0.0705882, 0.4784313725, 0.75294117647, 1
						background_color: [1, 1, 1, 0]
					Label: 
						text: 'Erkebispegården var fra gammelt av erkebiskopens bolig og administrative sentrum i Norge. Her er Norges riksregalier, orginalskulpturer fra Nidarosdomen og arkeologiske funn fra Erkebispegårdens historie utstilt.'
						text_size: self.width, None
						size_hint_y: None
						height: self.texture_size[1]
						color: 0.0705882, 0.4784313725, 0.75294117647, 1
						background_color: [1, 1, 1, 0]
				GridLayout:
					cols: 1
					rows: 1
					size_hint: (0.2, 0.5)

					Image:
						source: 'severdighetsbilder/erkebispegarden.jpg'
						allow_stretch: True
						keep_ratio: False

        Button:
            text: 'Til menyen'
            color: 0.0705882, 0.4784313725, 0.75294117647, 1
			background_color: [1, 1, 1, 0.1]
			font_size: 70
            on_press: root.manager.current = 'main'
            size_hint: (1, 0.2)




# Severdigheter - Info ------------------------------------------------------------------------

# ----------------Museum info-------------------

<RockheimInfo>:
	name: 'rockheiminfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'ROCKHEIM'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Det nasjonale museet for populærmusikk. Dra hit om du ønsker å lære mer om musikk, eller prøv deg som DJ, trommeslager og musikalsk kunstner selv!'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/rockheim.jpeg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'rockheim'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<TrondelagFolkemuseumInfo>:
	name: 'trondelagfolkemuseuminfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'TRØNDELAG FOLKEMUSEUM, SVERRESBORG'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Nysgjerrig på hvordan trønderne levde i gamle dager? I flotte historiske omgivelser kan du bli med på lefsekurs, eventyrstund eller byvandring for barn.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/trondelagfolkemuseum.png'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'trondelagFolkemuseum'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<RingveMuseumInfo>:
	name: 'ringvemuseuminfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'RINGVE MUSEUM'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Det nasjonale museet for musikk og musikkinstrumenter.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/ringvemuseum.png'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'ringveMuseum'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<VitenskapsmuseetInfo>:
	name: 'vitenskapsmuseetinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'VITENSKAPSMUSEET'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Vitenskapsmuseet har en rekke utstillinger, fra steinalderhistorie, til norges eldste jerv, som ble hele 20 år! Dyreliv, middelalderliv, livet i polhavet, det er ingen grense for hvor mye spennende man kan lære om ved å ta en tur til vitenskapsmuseet. Det er åpent tirsdag-fredag fra 10-16 og lørdag-søndag fra 11-16. Gratis for barn og ungdom under 18!'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/vitenskapsmuseet.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'vitenskapsmuseet'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<RustkammeretInfo>:
	name: 'rustkammeretinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'RUSTKAMMERET'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Allerede i 1826 ble Rustkammeret først brukt som museum. Den gang het det “Historiske våbensal”. Rustkammeret er et av forsvarets museer og utstillingene viser norsk motstandskamp helt fra vikingtiden til tiden da Norge var i union med Danmark.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/rustkammeret.JPG'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'rustkammeret'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<NordenfjeldskeKunstInfo>:
	name: 'nordenfjeldskekunstinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'NORDENFJELDSKE KUNSTINDUSTRIMUSEUM'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Nordenfjeldske Kunstindustrimuseet ble åpnet allerede i 1893 og har vært en samling av samtidskunst helt siden den tid. Blant annet var det på 1890-tallet svært populært med japansk kunst, og Nordenfjeldske har en imponerende samling av nettopp dette. For enhver kunstinteressert er dette et naturlig sted å ta turen.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/nordenfjeldske.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'nordenfjeldskeKunst'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'

<NorskDovemuseumInfo>:
	name: 'norskdovemuseuminfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'NORSK DØVEMUSEUM'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Norsk døvemuseum samler kulturhistorie, viktige gjenstander og har en dyp historisk bildesamling som representerer og ivaretar kulturarven for norske døve. Museet jobber med tilrettelegging og tilgjengeliggjøring med fokus på likeverd, like muligheter, tilgjengelighet og tilrettelegging for alle i vårt samfunn.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/norskdovemuseum.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'norskeDovemuseum'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<TrondheimKunstmuseumInfo>:
	name: 'trondheimkunstmuseuminfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'TRONDHEIM KUNSTMUSEUM'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Trondheim kunstmuseum stiller både ut en imponerende samling av internasjonal og norsk kunst, samt samtidskunst. Her forenes lokal kunsthistorie med internasjonalt relevante verker. Museet har to visningssteder, i Bispegata og i Trenerys gate ved nedre elvehavn.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/trondheimkunstmuseum.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'trondheimKunstmuseum'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<JodiskMuseumInfo>:
	name: 'jodiskmuseuminfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'JØDISK MUSEUM'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'I 1924 kjøpte Det Mosaiske Trossamfunn Trondheims første jernbanestasjon, og ombygde det til Europas nordligste synagoge. Museet var en gave til byen ved tusenårsjubileet i 1997, og forteller om historien og kulturen til de jødiske i det nordenfjeldske området, både før, under og etter andre verdenskrig.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/                                                                                                                                                                                                                                                                                                                                                         museum.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'jodiskeMuseum'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<TrondheimSjofartsmuseumInfo>:
	name: 'trondheimsjofartsmuseuminfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'TRONDHEIM SJØFARTSMUSEUM'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Trondheim Sjøfartsmuseum ble etablert i 1919, og formidler den maritime historien til Trondheim og omegn. Muséet holder til i et av de eldste murhusene i Trondheim kalt “Brattørvakta”, som også er fredet. Her kan du finne alt fra bilder av skuter og mannskap, til gammelt utstyr og dagbøker.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/TrondheimSjøfartsmuseum.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'trondheimSjofartsmuseum'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


# ----------------Historiske steder info-------------------

<NidarosdomenInfo>:
	name: 'nidarosdomeninfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'NIDAROSDOMEN'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Den praktfulle Nidarosdomen er Norges opprinnelige erkebiskopkirke, og en av nordens største middelalderkirker. Byggingen ble påbegynt i 1070, og domen har siden stått oppreist over Olav den Helliges grav. Flere av Norges konger er både kronet, viet og gravlagt her. Her kan du delta på både gudstjenester, omvisninger og konserter.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/Nidarosdomen.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'nidarosdomen'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<StiftsgardenInfo>:
	name: 'stiftsgardeninfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'STIFTSGÅRDEN'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Stiftsgården er Trondheims kongelige residens, og nordens største trepalé. Gården ble bygget for Cecilie Christine Schøller i 1774-1778. Du kan oppleve den barokk-klassisistiske stilen på Stiftsgården ved å delta på omvisning.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/stiftsgarden.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'stiftsgarden'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<GamleBybroInfo>:
	name: 'gamlebybroinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'GAMLE BYBRO'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Gamle Bybro, også kalt “Lykkens Portal”, strekker seg over nidelven ved Bakklandet. Den ble første gang bygget i forbindelse med Kristiansten festning i 1681, og skulle erstatte den tidligere bybroen. Dagens versjon av broen er fra 1861, og hadde opprinnelig broklapper som kunne heises opp og holdes oppe av to utskårne portalene, hvor én av dem fortsatt står igjen.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/GamleBybro.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'gamleBybro'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<KristianstenFestningInfo>:
	name: 'kristianstenfestninginfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'KRISTIANSTEN FESTNING'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Kristiansten festning har siden slutten av 1600-tallet stått over Bakklandet i Trondheim, og voktet over Gamle Bybro. Frem til 2001 har Kristiansten blant annet vært benyttet til militært bruk, treningsanlegg, brannvakt og rettersted. I dag er Kristiansten festning administrativt fredet og et av Norges 14 nasjonale festningsverk.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/KristianstenFestning.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'kristianstenFestning'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<ErkebispegardenInfo>:
	name: 'erkebispegardeninfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'ERKEBISPEGÅRDEN'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Erkebispegården var fra gammelt av erkebiskopens bolig og administrative sentrum i Norge. Her er Norges riksregalier, orginalskulpturer fra Nidarosdomen og arkeologiske funn fra Erkebispegårdens historie utstilt.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/erkebispegarden.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'erkebispegarden'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'



<MunkholmenInfo>:
	name: 'munkholmeninfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'MUNKHOLMEN'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Munkholmen er en holme i Trondheimsfjorden like utenfor Trondheim sentrum. Historisk ble holmen kalt Nidarholm og brukt som rettersted under vikingtiden. Da det senere ble bygget et klosteranlegg her fikk holmen navnet Munkholmen. Munkholmen har også vært brukt som festning og fengsel. I dag kan du dra ut hit for å bade, spise, delta på omvisning og nyte omgivelsene.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/Munkholmen.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'munkholmen'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<BakklandetInfo>
	name: 'bakklandetinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'BAKKLANDET'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Bakklandet er Trondheims gamle bydel, som ble bebygd først på tidlig 1600-tallet. Etter bydelen brant ned i 1718, ble den raskt gjenreist i form av små trehus, bryggerekke og brosteinsbelagte gater, som står i dag. Her kan du oppleve en koselig atmosfære med shopping, kaféer, restauranter og barer.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/Bakklandet.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'bakklandet'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<VarFrueKirkeInfo>:
	name: 'varfruekirkeinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'VÅR FRUE KIRKE'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Vår Frue kirke er en åpen omsorgskirke hvor du kan tenne lys, be, ta en kopp kaffe eller te og møte andre mennesker. Den er drevet av Kirkens Bymisjon, og har stått i hjertet av Trondheim siden år 1207.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/varfruekirke.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'varFrueKirke'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


# ----------------Kultur info-------------------

<VitensenteretInfo>:
	name: 'vitensenteretinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'VITENSENTERET'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Vitensenteret er et populærvitenskapelig opplevelsessenter. Her kan både voksne og barn eksperimentere med matematikk, naturvitenskap og teknologi. Her kan også oppleves 360-kino og 3D-planetarium.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/Vitensenteret.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'vitensenteret'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'

<KunsthallTrondheimInfo>:
	name: 'kunsthalltrondheiminfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'KUNSTHALL TRONDHEIM'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Kunsthall Trondheim er en institusjon for samtidskunst på internasjonalt nivå. Her foregår det alt fra utstillinger, konserter, performancer, video screenings, foredrag og poesiopplesninger.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/KunsthallTrondheim.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'kunsthallTrondheim'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<LitteraturhusetTrondheimInfo>:
	name: 'litteraturhusettrondheiminfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'LITTERATURHUSET TRONDHEIM'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Litteraturhuset i Trondheim har arrangementer innen litteratur, samfunnsdebatter og forskningsformidling. Disse foregår i form av flere faste arrangementer ved navn “Professor på kafé”, “Litterært måltid” og “Barnas teselskap”.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/Litteraturhuset.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'litteraturhusetTrondheim'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<KultursenteretISAKInfo>:
	name: 'kultursenteretISAKinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'KULTURSENTERET ISAK'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Kultursenteret ISAK er Trondheims kultursenter for ungdom som vil utøve, produsere eller oppleve kultur. Her får du hjelp til å iverksette drømmen din ved å få låne lokaler og utstyr, samt å finne samarbeidspartnere og kunnskapen som trengs.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/KultursenteretISAK.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'kultursenteretISAK'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'

# ----------------Natur info-------------------

<BurmaklippenInfo>:
	name: 'burmaklippeninfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'BURMAKLIPPEN'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Burmaklippen ligger i Estenstadmarka i Trondheim, og gir utsikt ut over Dragvoll og Byåsen. Dette utsiktspunktet går også under navnet “mini-Trolltunga”, ettersom den består av en steinformasjon som strekker seg ut over en klippe.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/Burmaklippen.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'burmaklippen'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'



<GeitfjelletInfo>:
	name: 'geitfjelletinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'GEITFJELLET'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Geitfjellet et et av bymarkas fineste utsiktspunkt, hvor du kan se det meste av Trondheim. Toppen ligger 416 m.o.h. , og tar 30-60 minutter avhengig av hvor du starter turen fra.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/Geitfjellet.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'geitfjellet'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'



<VattakammenInfo>:
	name: 'vattakammeninfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'VÅTTAKAMMEN'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Våttakammen ligger 286 m.o.h. , og gir en flott utsikt over Ila og midtbyen. Denne turen byr på et variert terreng og er også fint egnet for barn. Fra gammelt av var Våttakammen en vardeplass hvor det bl tent bål for å varsle om krig og ufred.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/Vattakammen.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'vattakammen'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'



<LadestienInfo>:
	name: 'ladestieninfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'LADESTIEN'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Ladestien strekker seg 8 km i et lett terreng langs sjøen fra Ladehammerkaia til Charlottenlund. Dette er et av de mest populære utfartsområdene i Trondheim. Langs stien finnes du alt fra badestrender, kaféer og festningsverk fra krigen.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/Ladestien.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'ladestien'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


# ----------------Mat / Drikke info-------------------

<TyholttarnetInfo>:
	name: 'tyholttarnetinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'TYHOLTTÅRNET'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'I tyholttårnet kan du nyte god mat og drikke fra Egon restaurant, hele 74 meter over bakken. Med et gulv som roterer 360º ser du utover hele Trondheim by og horisont.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/Tyholttarnet.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'tyholttarnet'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<IlaBrannstasjonInfo>:
	name: 'ilabrannstasjoninfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'ILA BRANNSTASJON'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Ila brainnstasjon er en liten kulturkafe som fokuserer på det lokale. Her kan man nyte kald eller varm mat, gå på søndagsjazz eller kose seg i baren. Her er det kort mellom kulturinnslagene, og Ila brainnstasjon er en flott sted å reise for å trekke inn litt inspirasjon.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/IlaBrannstasjon.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'ilaBrannstasjoninfo'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<AntikvariatetInfo>:
	name: 'antikvariatetinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'ANTIKVARIATET'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Det årne sæ, antikvariatet elske dæ uansett, står det på veggen i dette herlige lokalet. Nydelig dekor, og en kulturstrøm som er nesten uvirkelig, antikvariatet er et av de hyggeligste stedene i byen. Hver dag i uken.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/Antikvariatet.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'antikvariatet'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<ArvesolvetFolkekafeInfo>:
	name: 'arvesolvetfolkekafeinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'ARVESØLVET FOLKEKAFÈ'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Hos Arvesølvet folkekafé kan du nyte god mat laget fra bunnen av, som vekker gamle minner. I en retro atmosfære kan du få både frokost, lunsj og middag.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/ArvesolvetFolkekafe.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'arvesolvetFolkekafeinfo'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<CafeNimInfo>:
	name: 'cafeniminfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'CAFÈ NIM'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Café Nim bringer sammen kultur fra forskjellige land, og serverer småretter sammen med drikke både med og uten alkohol. Her kan du ta med deg vorspielet og oppleve kulturelle arrangementer som karaoke, musikk, trylleshow, stand-up og mye mer.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/CafeNim.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'cafeNim'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<CafeNiMuserInfo>:
	name: 'cafenimuserinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'CAFÈ NI MUSER'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Café Ni Muser er en uformell og trendy kunstkafe, og et av Trondheims beste konditori. Her finner du både kurs, konserter, temakvelder og utstillinger sammen med mat av lokale råvarer.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/CafeNiMuser.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'cafeNiMuser'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<RosenborgDampbakeriInfo>:
	name: 'rosenborgdampbakeriinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'ROSENBORG DAMPBAKERI'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Rosenborg Dampbakeri har vært i Trondheim siden 1902, og stiller med brød og kaker bakt på tradisjonelt håndverksvis. Dette bakeriet har gjennom fire generasjoner vært drevet av familien Helgesen.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/RosenborgDamp.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'rosenborgDampbakeri'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<SellenraaBokBarInfo>:
	name: 'sellenraabokbarinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'SELLANRAA BOK & BAR'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Sellanraa Bok & Bar ligger i den gamle brannstasjonen som i dag er blitt en blanding av bokhandel, kafé og restaurant.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/SellanraaBokBar.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'sellenraaBokBar'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<TrondheimMikrobryggeriInfo>:
	name: 'trondheimmikrobryggeriinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'TRONDHJEM MIKROBRYGGERI'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Trondhjem Mikrobryggeri har vært i Trondheim siden 1998, og er den andre bryggeripuben som ble etablert her til lands. Her får du hjemmelaget øl og brennevin i flere sorter, sammen med både småretter og hovedretter.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/Mikrobryggeri.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'trondheimMikrobryggeri'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<CafeLokkaInfo>:
	name: 'cafelokkainfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'CAFÈ LØKKA'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'I vintage interiør og god stemning hos Café Løkka på Solsiden kan du nyte en 60-talls inspirert meny både ute og inne. I 2011 ble denne kaféen kåret til årets beste utested/bar.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/CafeLokka.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'cafeLokka'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<BakklandetSkydsstasjonInfo>:
	name: 'bakklandetskydsstasjoninfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'BAKLANDET SKYDSSTATION'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Baklandet Skydsstation er en fredelig og idyllisk kafé, som serverer mat og drikke i gamle omgivelser. Kaféen ble i 2012 kåret til Årets Kafé av National Geographic, og er både nevnt av Andrew Evans’ i hans jordomfattende reiseblodd, og i Lonely Planet.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/BakklandetSkyds.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'bakklandetSkydsstasjon'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


# ----------------Aktiviteter info-------------------


<KlatresenterInfo>:
	name: 'klatresenterinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'KLATRESENTER'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Trondheims Klatresenter er kåret til Norges største og beste buldresenter. Her finner du buldrevegger i alle slags vanskelighetsgrader for både liten og stor, i tillegg til en tauvegg.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/Klatresenter.png'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'klatresenter'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'

<TurnhallInfo>:
	name: 'turnhallinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'TURNHALL'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Turnhallen i Trondheim sentrum tilbyr turn for yngre, men også kurs for nybegynnere til litt øvede i alle aldre.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/Turnhall.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'turnhall'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<BowlingInfo>:
	name: 'bowlinginfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'BOWLING'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Centrum Bowling ligger ved Trondheim Torg og har tilbudt bowling i over 40 år. Her får du servert mat og drikke til en runde med discobowling, familiebowling, bursdagsbowling, og mer.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/CentrumBowling.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'bowling'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<TrampolineparkInfo>:
	name: 'trampolineparkinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'TRAMPOLINEPARK'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Rush Trampolinepark ligger på Tiller og har er en innendørs aktivitetspark med trampoliner på vegger og gulv. De tilbyr frihopping, bursdager, babysprett, rush after dark (discotema), trampolinekurs og dodgeball liga.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/trampolinepark.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'trampolinepark'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<GokartOgLazerxInfo>:
	name: 'gokartoglazerxinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'GOKART OG LAZERX'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'På Fossegrenda kan du og familien eller vennegjengen utfordre hverandre til gokart og lasermaxx hos Lazerx Gokart Senter. Gokartbanen er Trondheims lengste innendørs bane. Liker du adrenalin byr lasermaxx på en real life spillopplevelse, hvor du sniker seg rundt i røyk og jakter på motstanderen med laserpistol.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/Gokart.jpg'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'gokartOgLazerx'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


<EscapeRealityInfo>:
	name: 'escaperealityinfo'

	canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

    	    Label:
    	        text: 'ESCAPE REALITY'
    	        font_size: 70
    	        color: 0.0705882, 0.4784313725, 0.75294117647, 1
        		size_hint: (1, 0.2)

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 1)
			cols: 2
			rows: 1

			Label:
			    padding: [100, 10]
			    text: 'Escape Reality byr på intense og nervepirrende opplevelser i Trondheim sentrum. Her skal grupper på 2-6 personer ha i oppgave å komme seg ut av et rom kun ved hjelp av gjenstandene i rommet, og det på kun 60 minutter.'
			    font_size: 30
			    text_size: self.size
			    color: 0.0705882, 0.4784313725, 0.75294117647, 1
			    halign: 'left'
			    valign: 'middle'

			Image:
				source: 'severdighetsbilder/EscapeReality.png'
				allow_stretch: True
				keep_ratio: False

		GridLayout:
			orientation: 'vertical'
			size_hint: (1, 0.11)
			cols: 3
			rows: 1

	        Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
            Button:
                text: 'Finn veien!'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'escapeReality'
            Button:
                text: 'Ny severdighet'
                size: root.size
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'SelectionScreen'


#-----------------------------------------------------------------------------------------------------
<Veibeskrivelser>:
	name: 'veibeskrivelser'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size: root.size
			rows: 2

			Label:
				text: "Veibeskrivelser"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
			Label:
				text: "Velg katergori"
				font_size: 30
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			cols: 3
			rows: 2

			Button:
				text: 'Museum'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'museum'
			Button:
				text: 'Historiske steder'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'historiskeSteder'
			Button:
				text: 'Kultur'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'kultur'
			Button:
				text: 'Natur'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'natur'
			Button:
				text: 'Mat og drikke'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'matDrikke'
			Button:
				text: "Aktiviteter"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'aktiviteter'



		GridLayout:
			size: root.size
			rows: 2

			Label:

			Button:
				text: "Tilbake til menyen"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				font_size: 70
				on_press: root.manager.current = 'main'

#-----------------------------------------------------------------------------------------------------------
<Museum>:
	name: 'museum'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size: root.size
			rows: 2

			Label:
				text: "Veibeskrivelser"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
			Label:
				text: "Museum"
				font_size: 30
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			cols: 3
			rows: 4

			Button:
				text: 'Rockheim'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'rockheim'
			Button:
				text: 'Trøndelag folkemuseum'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'trondelagFolkemuseum'
			Button:
				text: 'Ringve Museum'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'ringveMuseum'
			Button:
				text: 'Vitenskapsmuseet'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'vitenskapsmuseet'
			Button:
				text: 'Rustkammeret'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'rustkammeret'
			Button:
				text: 'Nordenfjeldske Kunstindustrimuseet'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'nordenfjeldskeKunst'
			Button:
				text: 'Norsk døvemuseum'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'norskeDovemuseum'
			Button:
				text: 'Trondheim kunstmuseum'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'trondheimKunstmuseum'
			Button:
				text: 'Jødisk museum'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'jodiskeMuseum'
			Button:
				text: 'Trondheim sjøfartsmuseum'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'trondheimSjofartsmuseum'
			Button:
				text: ''
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
			Button:
				text: ''
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]



		GridLayout:
			size: root.size
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'veibeskrivelser'



<Rockheim>:
	name: 'rockheim'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Rockheim"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake til menyen"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'main'




<TrondelagFolkemuseum>:
	name: 'trondelagFolkemuseum'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Trøndelag Folkemuseum"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake til menyen"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'main'


<RingveMuseum>:
	name: 'ringveMuseum'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Ringve Museum"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'museum'





<Vitenskapsmuseet>:
	name: 'vitenskapsmuseet'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Vitenskapsmuseet"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'museum'




<Rustkammeret>:
	name: 'rustkammeret'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Rustkammeret"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'museum'






<NordenfjeldskeKunst>:
	name: 'nordenfjeldskeKunst'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Nordenfjeldske Kunstmuseum"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'museum'



<NorskeDovemuseum>:
	name: 'norskeDovemuseum'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "norskeDøvemuseum"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'museum'





<TrondheimKunstmuseum>:
	name: 'trondheimKunstmuseum'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Trondheim Kunstmuseum"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'museum'




<JodiskeMuseum>:
	name: 'jodiskeMuseum'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Jødiske Museum"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'museum'






<Trondheimoartsmuseum>:
	name: 'trondheimSjofartsmuseum'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Trondheim Sjøfartsmuseum"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'museum'


#------------------------------------------------------------------------------------------------




<HistoriskeSteder>:
	name: 'historiskeSteder'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size: root.size
			rows: 2

			Label:
				text: "Veibeskrivelser"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
			Label:
				text: "Historiske steder"
				font_size: 30
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			cols: 3
			rows: 3

			Button:
				text: 'Nidarosdomen'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'nidarosdomen'
			Button:
				text: 'Stiftsgården'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'stiftsgarden'
			Button:
				text: 'Kristiansten festning'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'kristianstenFestning'
			Button:
				text: 'Erkebispegården'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'erkebispegarden'
			Button:
				text: 'Munkholmen'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'munkholmen'
			Button:
				text: 'Bakklandet'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'bakklandet'
			Button:
				text: 'Vår Frue kirke'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'varFrueKirke'
			Button:
				text: ''
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]




		GridLayout:
			size: root.size
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'veibeskrivelser'

#-------------------------------------------------------------------------------------------------------


<Nidarosdomen>:
	name: 'nidarosdomen'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Nidarosdomen"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'historiskeSteder'




<Stiftsgarden>:
	name: 'stiftsgarden'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Stiftsgården"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'historiskeSteder'





<GamleBybro>:
	name: 'gamleBybro'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "GamleBybro"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'historiskeSteder'





<KristianstenFestning>:
	name: 'kristianstenFestning'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Kristiansten Festning"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'historiskeSteder'





<Erkebispegarden>:
	name: 'erkebispegarden'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Erkebispegarden"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'historiskeSteder'





<Munkholmen>:
	name: 'munkholmen'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Munkholmen"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'historiskeSteder'



<Bakklandet>:
	name: 'bakklandet'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Bakklandet"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'historiskeSteder'





<VarFrueKirke>:
	name: 'varFrueKirke'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Vår Frue Kirke"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'historiskeSteder'




#---------------------------------------------------------------------------------------------------------




<Kultur>:
	name: 'kultur'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size: root.size
			rows: 2

			Label:
				text: "Veibeskrivelser"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
			Label:
				text: "Kultur"
				font_size: 30
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			cols: 2
			rows: 2

			Button:
				text: 'Vitensenteret'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'vitensenteret'
			Button:
				text: 'Kunsthall Trondheim'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'kunsthallTrondheim'
			Button:
				text: 'Litteraturhuset trondheim'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'litteraturhusetTrondheim'
			Button:
				text: 'Kultursenteret ISAK'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'kultursenteretISAK'




		GridLayout:
			size: root.size
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'veibeskrivelser'

#-----------------------------------------------------------------------------------------------




<Vitensenteret>:
	name: 'vitensenteret'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Vitensenteret"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'kultur'



<KunsthallTrondheim>:
	name: 'kunsthallTrondheim'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Kunsthall Trondheim"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'kultur'




<LitteraturhusetTrondheim>:
	name: 'litteraturhusetTrondheim'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Litteraturhuset Trondheim"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'kultur'




<KultursenteretISAK>:
	name: 'kultursenteretISAK'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Kultursenteret ISAK"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'kultur'





#------------------------------------------------------------------------------------------------




<Natur>:
	name: 'natur'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size: root.size
			rows: 2

			Label:
				text: "Veibeskrivelser"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
			Label:
				text: "Natur"
				font_size: 30
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			cols: 2
			rows: 2

			Button:
				text: 'Burmaklippen'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'burmaklippen'
			Button:
				text: 'Geitfjellet'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'geitfjellet'
			Button:
				text: 'Våttakammen'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'vattakammen'
			Button:
				text: 'Ladestien'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'ladestien'



		GridLayout:
			size: root.size
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'veibeskrivelser'

#-------------------------------------------------------------------------------------------------------



<Burmaklippen>:
	name: 'burmaklippen'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Burmaklippen"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'natur'



<Geitfjellet>:
	name: 'geitfjellet'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Geitfjellet"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'natur'



<Vattakammen>:
	name: 'vattakammen'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Våttakammen"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'natur'



<Ladestien>:
	name: 'ladestien'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Ladestien"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'natur'














#------------------------------------------------------------------------------------------------




<MatDrikke>:
	name: 'matDrikke'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size: root.size
			rows: 2

			Label:
				text: "Veibeskrivelser"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
			Label:
				text: "Mat og drikke"
				font_size: 30
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			cols: 3
			rows: 4

			Button:
				text: 'Tyholttarnet'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'tyholttarnet'
			Button:
				text: 'Ila Brannstasjon'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'ilaBrannstasjon'
			Button:
				text: 'Antikvariatet'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'antikvariatet'
			Button:
				text: 'Arvesølvet Folkekafe'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'arvesolvetFolkekafe'
			Button:
				text: 'Cafe Nim'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'cafeNim'
			Button:
				text: 'Cafe Ni Muser'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'cafeNiMuser'
			Button:
				text: 'RosenborgDampbakeri'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'rosenborgDampbakeri'
			Button:
				text: 'Sellenraa Bok & Bar'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'sellenraaBokBar'
            Button:
				text: 'Trondheim Mikrobryggeri'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'trondheimMikrobryggeri'
            Button:
				text: 'Cafe Lokka'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'cafeLokka'
            Button:
				text: 'Bakklandet Skydsstasjon'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'bakklandetSkydsstasjon'





		GridLayout:
			size: root.size
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'veibeskrivelser'

#-------------------------------------------------------------------------------------------------------



<Tyholttarnet>:
	name: 'tyholttarnet'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Tyholttårnet"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'matDrikke'


<IlaBrannstasjon>:
	name: 'ilaBrannstasjon'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Ila Brannstasjon"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'matDrikke'


<Antikvariatet>:
	name: 'antikvariatet'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Antikvariatet"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'matDrikke'


<ArvesolvetFolkekafe>:
	name: 'arvesolvetFolkekafe'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Arvesølvet Folkekafe"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'matDrikke'


<CafeNim>:
	name: 'cafeNim'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Cafe Nim"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'matDrikke'


<CafeNiMuser>:
	name: 'cafeNiMuser'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Cafe Ni Muser"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'matDrikke'


<RosenborgDampbakeri>:
	name: 'rosenborgDampbakeri'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Rosenborg Dampbakeri"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'matDrikke'


<SellenraaBokBar>:
	name: 'sellenraaBokBar'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Sellenraa Bok & Bar"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'matDrikke'


<TrondheimMikrobryggeri>:
	name: 'trondheimMikrobryggeri'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Trondheim Mikrobryggeri"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'matDrikke'


<CafeLokka>:
	name: 'cafeLokka'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Cafe Lokka"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'matDrikke'


<BakklandetSkydsstasjon>:
	name: 'bakklandetSkydsstasjon'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Bakklandet Skydsstasjon"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'matDrikke'






#------------------------------------------------------------------------------------------------




<Aktiviteter>:
	name: 'aktiviteter'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


	BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size: root.size
			rows: 2

			Label:
				text: "Veibeskrivelser"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
			Label:
				text: "Aktiviteter"
				font_size: 30
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			cols: 2
			rows: 3


			Button:
				text: 'Klatresenter'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'klatresenter'
			Button:
				text: 'Turnhall'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'turnhall'
			Button:
				text: 'Bowling'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'bowling'
			Button:
				text: 'Trampolinepark'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'trampolinepark'
			Button:
				text: 'Gokart og Lazerx'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'gokartOgLazerx'
			Button:
				text: 'Escape Reality'
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				on_press: root.manager.current = 'escapeReality'





		GridLayout:
			size: root.size
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'veibeskrivelser'

#-------------------------------------------------------------------------------------------------------




<Klatresenter>:
	name: 'klatresenter'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Klatresenter"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'aktiviteter'



<Turnhall>:
	name: 'turnhall'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Turnhall"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'aktiviteter'



<Bowling>:
	name: 'bowling'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Bowling"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'aktiviteter'



<Trampolinepark>:
	name: 'trampolinepark'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Trampolinepark"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'aktiviteter'



<GokartOgLazerx>:
	name: 'gokartOgLazerx'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Gokart og Lazerx"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'aktiviteter'



<EscapeReality>:
	name: 'escapeReality'
    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size


    BoxLayout:
		orientation: 'vertical'

		GridLayout:
			size_hint: (1, 0.3)
			rows: 1

			Label:
				text: "Escape Reality"
				font_size: 150
				color: 0.0705882, 0.4784313725, 0.75294117647, 1


		GridLayout:
			orientation: 'vertical'
			size: root.size
			rows: 1


			Image:
				source: 'VeibeskrivelserBilde/NidarosDomkirke.PNG'
				allow_stretch: True
				keep_ratio: True


		GridLayout:
			size_hint: (1, 0.15)
			rows: 2

			Label:

			Button:
				text: "Tilbake"
				color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0]
				on_press: root.manager.current = 'aktiviteter'





<CustomParkControl>:
	name: "parkkontroll"

    canvas.before:
        Color:
            rgba: 0.976470588, 0.976470588, 0.976470588, 1
        Rectangle:
            pos: self.pos
            size: self.size
    #slider_colors: 1,0,0
    #canvas.before:
       # Color:
       # rgba: root.slider_colors
      #  Rectangle:
      #  pos: root.pos
       # size: root.size
    BoxLayout:
        orientation: 'vertical'
#--TITTEL------------------------------------------------------
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 0.13
            cols: 1
            rows: 1
            Label:
                text: "Tilpass parken selv"
                #font_name: AncientMedium
                font_size: 100
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
#--OVERSKRIFTER------------------------------------------------------
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 0.1
            BoxLayout:
                orientation: 'horizontal'
                size_hint_y: 0.1
                Label:
                    size_hint_x: 0.02
                Label:
                    text: "LED"
                    font_size: 40
                    color: 0.0705882, 0.4784313725, 0.75294117647, 1
                    size_hint_x: 0.08
                Label:
                    size_hint_x: 0.02
                Label:
                    text: "Velg farge"
                    font_size: 40
                    color: 0.0705882, 0.4784313725, 0.75294117647, 1
                    #size_hint_x: 2
                Label:
                    size_hint_x: 0.02
                Label:
                    text: "Velg lyd"
                    font_size: 40
                    color: 0.0705882, 0.4784313725, 0.75294117647, 1
                    size_hint_x: 0.3
                Label:
                    size_hint_x: 0.02
                Label:
                    text: "Velg bilde"
                    font_size: 40
                    color: 0.0705882, 0.4784313725, 0.75294117647, 1
                    size_hint_x: 0.3

        BoxLayout:
            orientation: 'horizontal'
#--VENSTRE KANT---------------------------------------------
            BoxLayout:
                size_hint_x: 0.02
#--LED------------------------------------------------------
            BoxLayout:
                orientation: 'vertical'
                size_hint_x: 0.08

                ToggleButton:
                    id: LED # en id gjer at vi kan referere til widgeten
                    text: "1"
                    group: LED
                    font_size: 60
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_down: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    on_state: root.selectedLED(1)
                Label:
                    size_hint_y: 0.05
                ToggleButton:
                    id: LED11
                    text: "2"
                    group: LED
                    font_size: 60
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_down: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    on_state: root.selectedLED(11)
                Label:
                    size_hint_y: 0.05
                ToggleButton:
                    id: LED21
                    text: "3"
                    group: LED
                    font_size: 60
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_down: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    on_state: root.selectedLED(21)
                Label:
                    size_hint_y: 0.05
                ToggleButton:
                    id: LED31
                    text: "4"
                    group: LED
                    font_size: 60
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_down: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    on_state: root.selectedLED(31)
                Label:
                    size_hint_y: 0.05
                ToggleButton:
                    id: LED41
                    text: "5"
                    group: LED
                    font_size: 60
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_down: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    on_state: root.selectedLED(41)
                Label:
                    size_hint_y: 0.05
                ToggleButton:
                    id: LED51
                    text: "6"
                    group: LED
                    font_size: 60
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_down: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    on_state: root.selectedLED(51)
                Label:
                    size_hint_y: 0.05
                ToggleButton:
                    id: LED61
                    text: "7"
                    group: LED
                    font_size: 60
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_down: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    on_state: root.selectedLED(61)
                Label:
                    size_hint_y: 0.05
                ToggleButton:
                    id: LED71
                    text: "8"
                    group: LED
                    font_size: 60
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_down: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    on_state: root.selectedLED(71)
                Label:
                    size_hint_y: 0.05
                ToggleButton:
                    id: LED81
                    text: "9"
                    group: LED
                    font_size: 60
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_down: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    on_state: root.selectedLED(81)
                Label:
                    size_hint_y: 0.05
                ToggleButton:
                    id: LED10
                    text: "10"
                    group: LED
                    font_size: 60
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_down: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    on_state: root.selectedLED(91)
                Label:
                    size_hint_y: 0.05
                ToggleButton:
                    id: LEDAlle
                    text: "Alle"
                    group: LED
                    font_size: 50
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_down: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/LEDoff3.png'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/LEDon3.png'
                    on_state: root.selectedLED(10)
#--MELLOM LED OG FARGE---------------------------------------------
            BoxLayout:
                size_hint_x: 0.02
#--FARGE------------------------------------------------------
            BoxLayout:
                orientation: 'vertical'
                #size_hint_x: 2
                height: sp(30)
                size_hint_y: 1

                BoxLayout:
                    orientation: 'horizontal'
            #--Kolonne 1-----------
                    BoxLayout:
                        orientation: 'vertical'
                        Button:
                            background_color: [0, 0, 255, 1]
                            on_press: root.colorSelected(0,0,255)
                            on_press: root.lastButtonIneraction(0)
                        Button:
                            background_color: [0, 255, 0, 1]
                            on_press: root.colorSelected(0,0,255)
                            on_press: root.lastButtonIneraction(0)
                        Button:
                            background_color: [255, 0, 0, 1]
                            on_press: root.colorSelected(0,0,255)
                            on_press: root.lastButtonIneraction(0)
                        Button:
                            background_color: [255, 255, 0, 1]
                            on_press: root.colorSelected(0,0,255)
                            on_press: root.lastButtonIneraction(0)

            #--Kolonne 2-----------
                    BoxLayout:
                        orientation: 'vertical'
                        Button:
                            background_color: [0, 0, 128/255, 1]
                            on_press: root.colorSelected(0,0,128)
                            on_press: root.lastButtonIneraction(0)
                        Button:
                            background_color: [0, 255, 0, 1]
                            on_press: root.colorSelected(0,0,255)
                            on_press: root.lastButtonIneraction(0)
                        Button:
                            background_color: [255, 0, 0, 1]
                            on_press: root.colorSelected(0,0,255)
                            on_press: root.lastButtonIneraction(0)
                        Button:
                            background_color: [255, 255, 0, 1]
                            on_press: root.colorSelected(0,0,255)
                            on_press: root.lastButtonIneraction(0)

            #--Kolonne 3-----------
                    BoxLayout:
                        orientation: 'vertical'
                        Button:
                            background_color: [0, 130, 200, 1]
                            on_press: root.colorSelected(0,0,255)
                            on_press: root.lastButtonIneraction(0)
                        Button:
                            background_color: [0, 255, 0, 1]
                            on_press: root.colorSelected(0,255,0)
                            on_press: root.lastButtonIneraction(0)
                        Button:
                            background_color: [255, 0, 0, 1]
                            on_press: root.colorSelected(0,0,255)
                            on_press: root.lastButtonIneraction(0)
                        Button:
                            background_color: [255, 255, 0, 1]
                            on_press: root.colorSelected(0,0,255)
                            on_press: root.lastButtonIneraction(0)

            #--Kolonne 4-----------
                    BoxLayout:
                        orientation: 'vertical'
                        Button:
                            background_color: [0, 0, 255, 1]
                            on_press: root.colorSelected(0,0,255)
                            on_press: root.lastButtonIneraction(0)
                        Button:
                            background_color: [0, 255, 0, 1]
                            on_press: root.colorSelected(0,255,0)
                            on_press: root.lastButtonIneraction(0)
                        Button:
                            background_color: [255, 0, 0, 1]
                            on_press: root.colorSelected(0,0,255)
                            on_press: root.lastButtonIneraction(0)
                        Button:
                            background_color: [255, 255, 0, 1]
                            on_press: root.colorSelected(0,0,255)
                            on_press: root.lastButtonIneraction(0)




         #--Sliders-----------
                BoxLayout:
                    orientation: 'horizontal'
                    #height: sp(20)
                    size_hint_y: 0.15
                    canvas.before:
                        Color:
                            rgba: 0.976470588, 0.976470588, 0.976470588, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size

                #--Slider 1-----------
                    BoxLayout:
                        orientation: 'vertical'
                        Label:
                            text: 'Rød = %s' % int(s1.value)
                            color: 255/255, 0/255, 0/255, 1
                            font_size: 20
                            size_hint_y: 0.145
                        Slider:
                            id: s1
                            color: 0/255, 255/255, 0/255, 1
                            value: 122
                            range: (0,255)
                            step: 1
                            size_hint_y: 0.12
                            on_value: root.sliderValue(1, int(s1.value))
                            on_value: root.lastButtonIneraction(1)
                            #on_release: root.lastButtonIneraction(1)
                #--Slider 2-----------
                    BoxLayout:
                        orientation: 'vertical'
                        Label:
                            text: 'Grønn = %s' % int(s2.value)
                            color: 0/255, 255/255, 0/255, 1
                            font_size: 20
                            size_hint_y: 0.145
                        Slider:
                            id: s2
                            color: 0/255, 0/255, 255/255, 1
                            value: 122
                            range: (0,255)
                            step: 1
                            size_hint_y: 0.12
                            on_value: root.sliderValue(2, int(s2.value))
                            on_value: root.lastButtonIneraction(1)
                            #on_touch_up: root.lastButtonIneraction(1)
                #--Slider 3-----------
                    BoxLayout:
                        orientation: 'vertical'
                        Label:
                            text: 'Bla = %s' % int(s3.value)
                            color: 0/255, 0/255, 255/255, 1
                            font_size: 20
                            size_hint_y: 0.145
                        Slider:
                            id: s3
                            color: 0.03137, 0.32549, 0.46666666666, 1
                            value: 122
                            range: (0,255)
                            step: 1
                            size_hint_y: 0.12
                            on_value: root.sliderValue(3, int(s3.value))
                            on_value: root.lastButtonIneraction(1)
                            #on_touch_up: root.lastButtonIneraction(1)

            #--Valgt Farge-----------
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_y: 0.075
                    canvas.before:
                        Color:
                            rgba: int(s1.value)/255, int(s2.value)/255, int(s3.value)/255, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    Label:
                        text: "Valgt farge - en kombinasjon av rod, gronn og bla"
#--MELLOM FARGE OG LYD---------------------------------------------
            BoxLayout:
                size_hint_x: 0.02
#--LYD------------------------------------------------------
            BoxLayout:
                orientation: 'vertical'
                size_hint_x: 0.3

                ToggleButton:
                    id: Lyd
                    text: "Afrika"
                    group: Lyd
                    font_size: 20
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/africa.jpg'
                    background_down: 'KlimaFrontEnd/Bilder/africa2.jpg'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/africa2.jpg'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/africa.jpg'
                    on_press: root.selectedSound(1)
                Label:
                    size_hint_y: 0.075
                ToggleButton:
                    id: Lyd2
                    text: "Syden"
                    group: Lyd
                    font_size: 20
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/syden.jpg'
                    background_down: 'KlimaFrontEnd/Bilder/syden2.jpg'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/syden2.jpg'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/syden.jpg'
                    on_press: root.selectedSound(2)
                Label:
                    size_hint_y: 0.075
                ToggleButton:
                    id: Lyd3
                    text: "Bolgeskvulp"
                    group: Lyd
                    font_size: 20
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/wave.jpg'
                    background_down: 'KlimaFrontEnd/Bilder/wave2.jpg'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/wave2.jpg'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/wave.jpg'
                    on_press: root.selectedSound(3)
                Label:
                    size_hint_y: 0.075
                ToggleButton:
                    id: Lyd4
                    text: "Vind"
                    group: Lyd
                    font_size: 20
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/vind.jpg'
                    background_down: 'KlimaFrontEnd/Bilder/vind2.jpg'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/vind2.jpg'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/vind.jpg'
                    on_press: root.selectedSound(4)
                Label:
                    size_hint_y: 0.075
                ToggleButton:
                    id: Lyd5
                    text: "Fuglekvitter"
                    group: Lyd
                    font_size: 20
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/fuglekvitter.jpg'
                    background_down: 'KlimaFrontEnd/Bilder/fuglekvitter2.jpg'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/fuglekvitter2.jpg'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/fuglekvitter.jpg'
                    on_press: root.selectedSound(5)
                Label:
                    size_hint_y: 0.075
                ToggleButton:
                    id: Lyd6
                    text: "Jungel"
                    group: Lyd
                    font_size: 20
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/appe.jpg'
                    background_down: 'KlimaFrontEnd/Bilder/appe2.jpg'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/appe2.jpg'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/appe.jpg'
                    on_press: root.selectedSound(6)
                Label:
                    size_hint_y: 0.075
                ToggleButton:
                    id: Lyd7
                    text: ""
                    group: Lyd
                    font_size: 20
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/elsyslogoen.png'
                    background_down: 'KlimaFrontEnd/Bilder/elsyslogoen2.png'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/elsyslogoen2.png'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/elsyslogoen.png'
                    on_press: root.selectedSound(7)
#--MELLOM FARGE OG LYD---------------------------------------------
            BoxLayout:
                size_hint_x: 0.02
#--BILDE------------------------------------------------------
            BoxLayout:
                orientation: 'vertical'
                size_hint_x: 0.3

                ToggleButton:
                    id: Bilde
                    text: "Orken"
                    group: Bilde
                    font_size: 20
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/orken.jpg'
                    background_down: 'KlimaFrontEnd/Bilder/orken2.jpg'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/orken2.jpg'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/orken.jpg'
                    on_press: root.selectedPicture(1)
                Label:
                    size_hint_y: 0.075
                ToggleButton:
                    id: Bilde2
                    text: "Strand"
                    group: Bilde
                    font_size: 20
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/strand.jpg'
                    background_down: 'KlimaFrontEnd/Bilder/strand2.jpg'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/strand2.jpg'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/strand.jpg'
                    on_press: root.selectedPicture(2)
                Label:
                    size_hint_y: 0.075
                ToggleButton:
                    id: Bilde3
                    text: "Hav"
                    group: Bilde
                    font_size: 20
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/hav.jpg'
                    background_down: 'KlimaFrontEnd/Bilder/hav2.jpg'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/hav2.jpg'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/hav.jpg'
                    on_press: root.selectedPicture(3)
                Label:
                    size_hint_y: 0.075
                ToggleButton:
                    id: Bilde4
                    text: "Himmel"
                    group: Bilde
                    font_size: 20
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/himmel.jpg'
                    background_down: 'KlimaFrontEnd/Bilder/himmel2.jpg'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/himmel2.jpg'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/himmel.jpg'
                    on_press: root.selectedPicture(4)
                Label:
                    size_hint_y: 0.075
                ToggleButton:
                    id: Bilde5
                    text: "Fjell"
                    group: Bilde
                    font_size: 20
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/fjell.jpg'
                    background_down: 'KlimaFrontEnd/Bilder/fjell2.jpg'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/fjell2.jpg'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/fjell.jpg'
                    on_press: root.selectedPicture(5)
                Label:
                    size_hint_y: 0.075
                ToggleButton:
                    id: Bilde6
                    text: "Jungel"
                    group: Bilde
                    font_size: 20
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/jungel.png'
                    background_down: 'KlimaFrontEnd/Bilder/jungel2.png'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/jungel2.png'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/jungel.png'
                    on_press: root.selectedPicture(6)
                Label:
                    size_hint_y: 0.075
                ToggleButton:
                    id: Bilde7
                    text: ""
                    group: Bilde
                    font_size: 20
                    outline_width: 3
                    outline_color: (0,0,255,1)
                    border: 0, 0, 0, 0
                    background_normal: 'KlimaFrontEnd/Bilder/ELSYS.PNG'
                    background_down: 'KlimaFrontEnd/Bilder/ELSYS5.PNG'
                    background_disabled_down: 'KlimaFrontEnd/Bilder/ELSYS5.PNG'
                    background_disabled_normal: 'KlimaFrontEnd/Bilder/ELSYS.PNG'
                    on_press: root.selectedPicture(7)
#--HØYREKANT---------------------------------------------
            BoxLayout:
                size_hint_x: 0.02
#--MENY------------------------------------------------------
        GridLayout:
            orientation: 'vertical'
            size_hint: (1, 0.07)
            cols: 1
            rows: 1

            Button:
                text: 'Tilbake til meny'
                size: root.size
                on_press: root.manager.current = 'main'
                color: 0.0705882, 0.4784313725, 0.75294117647, 1
				background_color: [1, 1, 1, 0.1]
				font_size: 70






